// playground/react/src/main.tsx
import { HijriCalendar, type HijriCalendarSize, type HijriCalendarTheme } from '@taqwim/react-styled'
import type { HijriDateObject } from '@taqwim/core'
import { StrictMode, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { formatSelection, readConfig } from './harness'

/**
 * The React end of the shared end-to-end harness.
 *
 * Configuration comes from the query string so one Playwright spec can put
 * every framework's adapter into the same state. See `e2e/harness.ts`.
 */
function Harness() {
  const config = readConfig(window.location.search)
  const [theme, setTheme] = useState<HijriCalendarTheme>(config.theme as HijriCalendarTheme)
  const [value, setValue] = useState<HijriDateObject | HijriDateObject[] | undefined>(config.value)

  return (
    <>
      <select data-testid="theme" value={theme} onChange={event => setTheme(event.target.value as HijriCalendarTheme)}>
        {['default', 'dark', 'islamic', 'neon', 'ocean'].map(name => (
          <option key={name} value={name}>
            {name}
          </option>
        ))}
      </select>

      <HijriCalendar
        theme={theme}
        size={config.size as HijriCalendarSize}
        locale={config.locale}
        dir={config.dir}
        weekStartsOn={config.weekStartsOn as 0}
        numberOfMonths={config.numberOfMonths}
        fixedWeeks={config.fixedWeeks}
        multiple={config.multiple}
        preventDeselect={config.preventDeselect}
        disableDaysOutsideCurrentView={config.disableDaysOutsideCurrentView}
        disabled={config.disabled}
        readonly={config.readonly}
        initialFocus={config.initialFocus}
        defaultPlaceholder={config.placeholder}
        minValue={config.min}
        maxValue={config.max}
        value={value}
        onValueChange={setValue}
      />

      <output data-testid="selection">{formatSelection(value)}</output>
    </>
  )
}

createRoot(document.getElementById('app')!).render(
  <StrictMode>
    <Harness />
  </StrictMode>,
)

// playground/solid/src/main.tsx
import type { HijriDateObject } from '@taqwim/core'
import { HijriCalendar, type HijriCalendarSize, type HijriCalendarTheme } from '@taqwim/solid-styled'
import { createSignal, For } from 'solid-js'
import { render } from 'solid-js/web'
import { formatSelection, readConfig } from './harness'

/**
 * The Solid end of the shared end-to-end harness.
 *
 * Configuration comes from the query string so one Playwright spec can put
 * every framework's adapter into the same state. See `e2e/harness.ts`.
 */
function Harness() {
  const config = readConfig(window.location.search)
  const [theme, setTheme] = createSignal<HijriCalendarTheme>(config.theme as HijriCalendarTheme)
  const [value, setValue] = createSignal<HijriDateObject | HijriDateObject[] | undefined>(config.value)

  return (
    <>
      <select
        data-testid="theme"
        value={theme()}
        onChange={event => setTheme(event.currentTarget.value as HijriCalendarTheme)}
      >
        <For each={['default', 'dark', 'islamic', 'neon', 'ocean']}>{name => <option value={name}>{name}</option>}</For>
      </select>

      <HijriCalendar
        theme={theme()}
        size={config.size as HijriCalendarSize}
        locale={config.locale}
        dir={config.dir}
        weekStartsOn={config.weekStartsOn as 0}
        numberOfMonths={config.numberOfMonths}
        fixedWeeks={config.fixedWeeks}
        multiple={config.multiple}
        preventDeselect={config.preventDeselect}
        disableDaysOutsideCurrentView={config.disableDaysOutsideCurrentView}
        disabled={config.disabled}
        readonly={config.readonly}
        initialFocus={config.initialFocus}
        defaultPlaceholder={config.placeholder}
        minValue={config.min}
        maxValue={config.max}
        value={value()}
        onValueChange={setValue}
      />

      <output data-testid="selection">{formatSelection(value())}</output>
    </>
  )
}

render(() => <Harness />, document.getElementById('app')!)
