// packages/react/src/HijriCalendar.tsx
import type { CalendarDay, CalendarMonth } from '@taqwim/calendar-core'
import type { ComponentPropsWithoutRef, KeyboardEvent, ReactNode } from 'react'
import { useEffect, useRef } from 'react'
import { HijriCalendarProvider, useHijriCalendarContext } from './context'
import type { HijriCalendarRootProps } from './types'
import { useCalendar } from './useCalendar'

type DivProps = Omit<ComponentPropsWithoutRef<'div'>, 'children' | 'dir'>
type ButtonProps = Omit<ComponentPropsWithoutRef<'button'>, 'children' | 'onClick' | 'type'>

/**
 * The store speaks DOM attribute names, which is what makes one stylesheet and
 * one e2e suite cover every framework. React wants `tabIndex`, so that single
 * key is renamed here rather than compromising the shared contract.
 */
function withReactCasing<T extends { tabindex: 0 | -1 }>({ tabindex, ...rest }: T) {
  return { ...rest, tabIndex: tabindex }
}

/*
 * Every part below spreads props the store computed. Because those are the same
 * `data-*` and `aria-*` attributes the Vue adapter emits, `@taqwim/themes`
 * styles both without a line of React-specific CSS, and one Playwright spec
 * covers both.
 */

/**
 * Which props belong to the state machine. Anything else a caller passes is a
 * DOM attribute and lands on the root element — React has no `$attrs`, so the
 * split has to be explicit.
 */
const OPTION_KEYS = new Set<string>([
  'defaultValue',
  'value',
  'onValueChange',
  'defaultPlaceholder',
  'placeholder',
  'onPlaceholderChange',
  'weekStartsOn',
  'weekdayFormat',
  'calendarLabel',
  'fixedWeeks',
  'numberOfMonths',
  'pagedNavigation',
  'multiple',
  'preventDeselect',
  'disableDaysOutsideCurrentView',
  'disabled',
  'readonly',
  'minValue',
  'maxValue',
  'locale',
  'dir',
  'isDateDisabled',
  'isDateUnavailable',
  'nextPage',
  'prevPage',
])

function splitProps(props: Record<string, unknown>) {
  const options: Record<string, unknown> = {}
  const domProps: Record<string, unknown> = {}

  for (const [key, value] of Object.entries(props)) {
    ;(OPTION_KEYS.has(key) ? options : domProps)[key] = value
  }

  return { options, domProps }
}

export function HijriCalendarRoot({ children, initialFocus, ...rest }: HijriCalendarRootProps & DivProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const pendingFocus = useRef<string | undefined>(undefined)

  const { options, domProps } = splitProps(rest as Record<string, unknown>)

  const { store, state } = useCalendar({
    ...options,
    onFocusedDateChange: date => {
      pendingFocus.current = date ? store.formatter.isoDate(date) : undefined
    },
  })

  // The store owns which date has focus; the adapter owns the DOM. Running
  // after commit means the target cell exists even when the move paged the
  // calendar into a month that was not rendered a moment ago.
  useEffect(() => {
    const value = pendingFocus.current
    if (!value) return
    pendingFocus.current = undefined

    rootRef.current?.querySelector<HTMLElement>(`[data-taqwim-calendar-cell-trigger][data-value="${value}"]`)?.focus()
  })

  const focusedOnMount = useRef(false)
  useEffect(() => {
    if (!initialFocus || focusedOnMount.current) return
    focusedOnMount.current = true
    store.focusInitial()
  }, [initialFocus, store])

  function onKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    if (store.handleKeydown(event)) event.preventDefault()
  }

  return (
    <HijriCalendarProvider value={{ store, state }}>
      <div {...store.getRootProps()} {...domProps} ref={rootRef} onKeyDown={onKeyDown}>
        {typeof children === 'function'
          ? children({ months: state.months, weekDays: state.weekDays, state, store })
          : children}

        {/* Inlined rather than classed: the headless package must not require a stylesheet. */}
        <div
          style={{
            position: 'absolute',
            width: 1,
            height: 1,
            padding: 0,
            margin: -1,
            overflow: 'hidden',
            clipPath: 'inset(50%)',
            whiteSpace: 'nowrap',
            border: 0,
          }}
        >
          <div role="heading" aria-level={2}>
            {state.fullCalendarLabel}
          </div>
        </div>
      </div>
    </HijriCalendarProvider>
  )
}

export function HijriCalendarHeader({ children, ...rest }: DivProps & { children?: ReactNode }) {
  const { state } = useHijriCalendarContext()

  return (
    <div role="group" aria-label={state.fullCalendarLabel} data-taqwim-calendar-header="" {...rest}>
      {children}
    </div>
  )
}

export function HijriCalendarHeading({
  children,
  ...rest
}: DivProps & { children?: ReactNode | ((headingValue: string) => ReactNode) }) {
  const { state } = useHijriCalendarContext()

  return (
    <div data-taqwim-calendar-heading="" data-disabled={state.disabled ? '' : undefined} {...rest}>
      {typeof children === 'function' ? children(state.headingValue) : (children ?? state.headingValue)}
    </div>
  )
}

export function HijriCalendarPrev({
  children,
  ...rest
}: ButtonProps & { children?: ReactNode | ((disabled: boolean) => ReactNode) }) {
  const { store, state } = useHijriCalendarContext()
  const disabled = state.isPrevDisabled

  return (
    <button {...store.getPrevButtonProps()} {...rest} disabled={disabled} onClick={store.prevPage}>
      {typeof children === 'function' ? children(disabled) : children}
    </button>
  )
}

export function HijriCalendarNext({
  children,
  ...rest
}: ButtonProps & { children?: ReactNode | ((disabled: boolean) => ReactNode) }) {
  const { store, state } = useHijriCalendarContext()
  const disabled = state.isNextDisabled

  return (
    <button {...store.getNextButtonProps()} {...rest} disabled={disabled} onClick={store.nextPage}>
      {typeof children === 'function' ? children(disabled) : children}
    </button>
  )
}

export function HijriCalendarGrid({
  month,
  children,
  ...rest
}: DivProps & {
  /** Optional for the single-month case, where it defaults to the only month. */
  month?: CalendarMonth
  children?: ReactNode | ((month: CalendarMonth) => ReactNode)
}) {
  const { store, state } = useHijriCalendarContext()
  const resolved = month ?? state.months[0]

  return (
    <div tabIndex={-1} {...store.getGridProps(resolved)} {...rest}>
      {typeof children === 'function' ? children(resolved) : children}
    </div>
  )
}

export function HijriCalendarGridHead({
  children,
  ...rest
}: DivProps & { children?: ReactNode | ((weekDays: string[]) => ReactNode) }) {
  const { state } = useHijriCalendarContext()

  // The weekday row duplicates each cell's accessible label, so it is hidden
  // from assistive technology rather than read out twice.
  return (
    <div aria-hidden="true" data-taqwim-calendar-grid-head="" {...rest}>
      {typeof children === 'function' ? children(state.weekDays) : children}
    </div>
  )
}

export function HijriCalendarGridBody({ children, ...rest }: DivProps & { children?: ReactNode }) {
  return (
    <div data-taqwim-calendar-grid-body="" {...rest}>
      {children}
    </div>
  )
}

export function HijriCalendarGridRow({ children, ...rest }: DivProps & { children?: ReactNode }) {
  return (
    <div role="row" data-taqwim-calendar-grid-row="" {...rest}>
      {children}
    </div>
  )
}

export function HijriCalendarHeadCell({ children, ...rest }: DivProps & { children?: ReactNode }) {
  return (
    <div data-taqwim-calendar-head-cell="" {...rest}>
      {children}
    </div>
  )
}

export function HijriCalendarCell({ day, children, ...rest }: DivProps & { day: CalendarDay; children?: ReactNode }) {
  return (
    <div
      role="gridcell"
      aria-selected={day.isSelected || undefined}
      aria-disabled={day.isDisabled || day.isUnavailable || undefined}
      data-taqwim-calendar-cell=""
      data-disabled={day.isDisabled ? '' : undefined}
      data-outside-month={day.isOutsideMonth ? '' : undefined}
      {...rest}
    >
      {children}
    </div>
  )
}

export function HijriCalendarCellTrigger({
  day,
  children,
  ...rest
}: ButtonProps & {
  day: CalendarDay
  children?: ReactNode | ((props: { dayValue: string; day: CalendarDay }) => ReactNode)
}) {
  const { store } = useHijriCalendarContext()
  const dayValue = store.formatter.dayOfMonth(day.date)

  function onClick() {
    // `select` re-checks these itself; this only avoids the pointless call.
    if (day.isDisabled || day.isUnavailable) return
    store.select(day.date)
  }

  function onFocus() {
    // Tabbing or clicking into a cell makes it the roving-focus target.
    // Re-reporting a date the store already holds would echo its own
    // programmatic `.focus()` back at it, so that case is skipped.
    if (day.isDisabled || day.isFocused) return
    store.focusDate(day.date)
  }

  return (
    <button {...withReactCasing(store.getCellTriggerProps(day))} {...rest} onClick={onClick} onFocus={onFocus}>
      {typeof children === 'function' ? children({ dayValue, day }) : (children ?? dayValue)}
    </button>
  )
}

// packages/solid/src/HijriCalendar.tsx
import type { CalendarDay, CalendarMonth } from '@taqwim/calendar-core'
import { createEffect, onMount, splitProps, type JSX } from 'solid-js'
import { HijriCalendarContext, useHijriCalendarContext } from './context'
import { OPTION_KEYS, type HijriCalendarRootProps } from './types'
import { createCalendarStore } from './useCalendar'

type DivProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, 'children'>
type ButtonProps = Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, 'children' | 'onClick' | 'type'>

/*
 * Every part below spreads props the store computed. Because those are the same
 * `data-*` and `aria-*` attributes the Vue and React adapters emit,
 * `@taqwim/themes` styles all of them and one Playwright spec covers all of
 * them.
 *
 * Props are never destructured — Solid props are getters, and destructuring
 * would read them once and lose reactivity.
 */

function renderChildren<T>(children: JSX.Element | ((props: T) => JSX.Element) | undefined, props: T): JSX.Element {
  return typeof children === 'function' ? (children as (props: T) => JSX.Element)(props) : children
}

export function HijriCalendarRoot(props: HijriCalendarRootProps): JSX.Element {
  const [options, local, domProps] = splitProps(props, OPTION_KEYS, ['children', 'initialFocus'])

  let rootElement: HTMLDivElement | undefined
  // Set by the store when the roving focus moves; consumed after the render.
  let pendingFocus: string | undefined

  const { store, state } = createCalendarStore(() => ({
    ...options,
    onFocusedDateChange: date => {
      pendingFocus = date ? store.formatter.isoDate(date) : undefined
    },
  }))

  /*
   * The store owns which date has focus; the adapter owns the DOM. Solid's
   * effects run after the DOM is updated, so the target cell exists even when
   * the move paged the calendar into a month that was not rendered a moment
   * ago.
   */
  createEffect(() => {
    // Read the state so this re-runs on every change.
    state()
    if (!pendingFocus) return

    const value = pendingFocus
    pendingFocus = undefined
    rootElement?.querySelector<HTMLElement>(`[data-taqwim-calendar-cell-trigger][data-value="${value}"]`)?.focus()
  })

  onMount(() => {
    if (local.initialFocus) store.focusInitial()
  })

  const onKeyDown: JSX.EventHandler<HTMLDivElement, KeyboardEvent> = event => {
    if (store.handleKeydown(event)) event.preventDefault()
  }

  return (
    <HijriCalendarContext.Provider value={{ store, state }}>
      <div ref={rootElement} {...store.getRootProps()} {...domProps} onKeyDown={onKeyDown}>
        {renderChildren(local.children, {
          get months() {
            return state().months
          },
          get weekDays() {
            return state().weekDays
          },
          get state() {
            return state()
          },
          store,
        })}

        {/* Inlined rather than classed: the headless package must not require a stylesheet. */}
        <div
          style={{
            position: 'absolute',
            width: '1px',
            height: '1px',
            padding: '0',
            margin: '-1px',
            overflow: 'hidden',
            'clip-path': 'inset(50%)',
            'white-space': 'nowrap',
            border: '0',
          }}
        >
          <div role="heading" aria-level={2}>
            {state().fullCalendarLabel}
          </div>
        </div>
      </div>
    </HijriCalendarContext.Provider>
  )
}

export function HijriCalendarHeader(props: DivProps & { children?: JSX.Element }): JSX.Element {
  const { state } = useHijriCalendarContext()
  const [local, rest] = splitProps(props, ['children'])

  return (
    <div role="group" aria-label={state().fullCalendarLabel} data-taqwim-calendar-header="" {...rest}>
      {local.children}
    </div>
  )
}

export function HijriCalendarHeading(
  props: DivProps & { children?: JSX.Element | ((headingValue: string) => JSX.Element) },
): JSX.Element {
  const { state } = useHijriCalendarContext()
  const [local, rest] = splitProps(props, ['children'])

  return (
    <div data-taqwim-calendar-heading="" data-disabled={state().disabled ? '' : undefined} {...rest}>
      {local.children === undefined ? state().headingValue : renderChildren(local.children, state().headingValue)}
    </div>
  )
}

export function HijriCalendarPrev(
  props: ButtonProps & { children?: JSX.Element | ((disabled: boolean) => JSX.Element) },
): JSX.Element {
  const { store, state } = useHijriCalendarContext()
  const [local, rest] = splitProps(props, ['children'])

  return (
    <button
      {...store.getPrevButtonProps()}
      {...rest}
      disabled={state().isPrevDisabled}
      onClick={() => store.prevPage()}
    >
      {renderChildren(local.children, state().isPrevDisabled)}
    </button>
  )
}

export function HijriCalendarNext(
  props: ButtonProps & { children?: JSX.Element | ((disabled: boolean) => JSX.Element) },
): JSX.Element {
  const { store, state } = useHijriCalendarContext()
  const [local, rest] = splitProps(props, ['children'])

  return (
    <button
      {...store.getNextButtonProps()}
      {...rest}
      disabled={state().isNextDisabled}
      onClick={() => store.nextPage()}
    >
      {renderChildren(local.children, state().isNextDisabled)}
    </button>
  )
}

export function HijriCalendarGrid(
  props: DivProps & {
    /** Optional for the single-month case, where it defaults to the only month. */
    month?: CalendarMonth
    children?: JSX.Element | ((month: CalendarMonth) => JSX.Element)
  },
): JSX.Element {
  const { store, state } = useHijriCalendarContext()
  const [local, rest] = splitProps(props, ['month', 'children'])
  const month = () => local.month ?? state().months[0]

  return (
    <div tabindex={-1} {...store.getGridProps(month())} {...rest}>
      {renderChildren(local.children, month())}
    </div>
  )
}

export function HijriCalendarGridHead(
  props: DivProps & { children?: JSX.Element | ((weekDays: string[]) => JSX.Element) },
): JSX.Element {
  const { state } = useHijriCalendarContext()
  const [local, rest] = splitProps(props, ['children'])

  // The weekday row duplicates each cell's accessible label, so it is hidden
  // from assistive technology rather than read out twice.
  return (
    <div aria-hidden="true" data-taqwim-calendar-grid-head="" {...rest}>
      {renderChildren(local.children, state().weekDays)}
    </div>
  )
}

export function HijriCalendarGridBody(props: DivProps & { children?: JSX.Element }): JSX.Element {
  const [local, rest] = splitProps(props, ['children'])

  return (
    <div data-taqwim-calendar-grid-body="" {...rest}>
      {local.children}
    </div>
  )
}

export function HijriCalendarGridRow(props: DivProps & { children?: JSX.Element }): JSX.Element {
  const [local, rest] = splitProps(props, ['children'])

  return (
    <div role="row" data-taqwim-calendar-grid-row="" {...rest}>
      {local.children}
    </div>
  )
}

export function HijriCalendarHeadCell(props: DivProps & { children?: JSX.Element }): JSX.Element {
  const [local, rest] = splitProps(props, ['children'])

  return (
    <div data-taqwim-calendar-head-cell="" {...rest}>
      {local.children}
    </div>
  )
}

export function HijriCalendarCell(props: DivProps & { day: CalendarDay; children?: JSX.Element }): JSX.Element {
  const [local, rest] = splitProps(props, ['day', 'children'])

  return (
    <div
      role="gridcell"
      aria-selected={local.day.isSelected || undefined}
      aria-disabled={local.day.isDisabled || local.day.isUnavailable || undefined}
      data-taqwim-calendar-cell=""
      data-disabled={local.day.isDisabled ? '' : undefined}
      data-outside-month={local.day.isOutsideMonth ? '' : undefined}
      {...rest}
    >
      {local.children}
    </div>
  )
}

export function HijriCalendarCellTrigger(
  props: ButtonProps & {
    day: CalendarDay
    children?: JSX.Element | ((props: { dayValue: string; day: CalendarDay }) => JSX.Element)
  },
): JSX.Element {
  const { store } = useHijriCalendarContext()
  const [local, rest] = splitProps(props, ['day', 'children'])
  const dayValue = () => store.formatter.dayOfMonth(local.day.date)

  function onClick() {
    // `select` re-checks these itself; this only avoids the pointless call.
    if (local.day.isDisabled || local.day.isUnavailable) return
    store.select(local.day.date)
  }

  function onFocus() {
    // Tabbing or clicking into a cell makes it the roving-focus target.
    // Re-reporting a date the store already holds would echo its own
    // programmatic `.focus()` back at it, so that case is skipped.
    if (local.day.isDisabled || local.day.isFocused) return
    store.focusDate(local.day.date)
  }

  return (
    <button {...store.getCellTriggerProps(local.day)} {...rest} onClick={onClick} onFocus={onFocus}>
      {local.children === undefined
        ? dayValue()
        : renderChildren(local.children, { dayValue: dayValue(), day: local.day })}
    </button>
  )
}
