// packages/vue-styled/src/HijriCalendar.vue
<script lang="ts">
import type { CalendarDay, HijriCalendarRootProps } from '@taqwim/vue'
import type { HijriDateObject } from '@taqwim/core'
import type { Component } from 'vue'

/*
 * Generated from the stylesheets in @taqwim/themes, so a new preset is one
 * CSS file rather than an identical edit in all five styled packages.
 */
import type { HijriCalendarLayout, HijriCalendarTheme } from '@taqwim/themes/names'

export type { HijriCalendarLayout, HijriCalendarTheme }

export type HijriCalendarSize = 'compact' | 'default' | 'large'

export interface HijriCalendarProps extends HijriCalendarRootProps {
  /**
   * Which bundled theme to render with.
   *
   * Applied as `data-taqwim-theme`, so it can also be set on any ancestor to
   * theme a whole subtree, and changed at runtime without swapping stylesheets.
   * @default 'default'
   */
  theme?: HijriCalendarTheme
  /** @default 'default' */
  size?: HijriCalendarSize
  /**
   * How the calendar is arranged.
   *
   * Applied as `data-taqwim-layout`, orthogonal to `theme` and `size` — a
   * theme sets colours, a size sets metrics, a layout sets arrangement.
   * `panel` keeps the grid visible while the month/year picker is open.
   * @default 'default'
   */
  layout?: HijriCalendarLayout
  /** Show the previous/next paging buttons. @default true */
  showNavigation?: boolean
  /** Show the weekday label row. @default true */
  showWeekdays?: boolean
  /**
   * Show the month and year as separate heading buttons that open their pickers.
   * @default true
   */
  selectableHeading?: boolean
  /** Replace the default chevrons. */
  navigationIcons?: { prev?: Component; next?: Component }
}

export interface HijriCalendarSlots {
  /** Replaces the whole header, including navigation. */
  header?: (props: { heading: string; prevPage: () => void; nextPage: () => void }) => unknown
  'prev-button'?: (props: { disabled: boolean }) => unknown
  'next-button'?: (props: { disabled: boolean }) => unknown
  weekday?: (props: { weekday: string; index: number }) => unknown
  /** Replaces the contents of a day cell. */
  cell?: (props: { dayValue: string; day: CalendarDay }) => unknown
}
</script>

<script setup lang="ts">
import { getLocaleData, MAX_HIJRI_YEAR, MIN_HIJRI_YEAR } from '@taqwim/core'
import {
  HijriCalendarCell,
  HijriCalendarCellTrigger,
  HijriCalendarGrid,
  HijriCalendarGridBody,
  HijriCalendarGridHead,
  HijriCalendarGridRow,
  HijriCalendarHeadCell,
  HijriCalendarHeader,
  HijriCalendarHeading,
  HijriCalendarNext,
  HijriCalendarPrev,
  HijriCalendarRoot,
} from '@taqwim/vue'
import { computed, ref } from 'vue'
import ArrowLeft from './icons/ArrowLeft.vue'
import ArrowRight from './icons/ArrowRight.vue'

const props = withDefaults(defineProps<HijriCalendarProps>(), {
  theme: 'default',
  size: 'default',
  layout: 'default',
  showNavigation: true,
  showWeekdays: true,
  selectableHeading: true,
})

defineSlots<HijriCalendarSlots>()

defineOptions({ name: 'HijriCalendar' })

const modelValue = defineModel<HijriDateObject | HijriDateObject[] | undefined>({ default: undefined })
const placeholder = defineModel<HijriDateObject | undefined>('placeholder', { default: undefined })

type Picker = 'month' | 'year' | null
const picker = ref<Picker>(null)

const months = computed(() => getLocaleData(props.locale ?? 'en', 'monthsLong') as string[])

/*
 * Bounded by what the Umm al-Qura table actually covers, rather than the
 * `new Date().getFullYear() + 579` approximation the previous version used —
 * that offered years the calendar cannot convert.
 */
const years = computed(() => Array.from({ length: MAX_HIJRI_YEAR - MIN_HIJRI_YEAR + 1 }, (_, i) => MIN_HIJRI_YEAR + i))

/*
 * Only the headless props are forwarded. The presentational ones are this
 * component's own, and `modelValue` / `placeholder` already flow through their
 * `v-model` bindings — spreading them again would shadow those bindings.
 */
const rootProps = computed(() => {
  const {
    theme: _theme,
    size: _size,
    layout: _layout,
    showNavigation: _showNavigation,
    showWeekdays: _showWeekdays,
    selectableHeading: _selectableHeading,
    navigationIcons: _navigationIcons,
    modelValue: _modelValue,
    placeholder: _placeholder,
    ...rest
  } = props
  return rest
})

function jumpTo(part: Partial<HijriDateObject>, current: HijriDateObject) {
  // Day 1 keeps the jump inside the target month regardless of its length.
  placeholder.value = { ...current, ...part, hd: 1 }
  picker.value = null
}

function togglePicker(which: 'month' | 'year') {
  picker.value = picker.value === which ? null : which
}
</script>

<template>
  <HijriCalendarRoot
    v-model="modelValue"
    v-model:placeholder="placeholder"
    v-bind="rootProps"
    :data-taqwim-theme="theme"
    :data-taqwim-size="size === 'default' ? undefined : size"
    :data-taqwim-layout="layout === 'default' ? undefined : layout"
    v-slot="{ months: visibleMonths, weekDays, state, store }"
  >
    <slot name="header" :heading="state.headingValue" :prev-page="store.prevPage" :next-page="store.nextPage">
      <HijriCalendarHeader class="taqwim-calendar-header">
        <HijriCalendarPrev v-if="showNavigation" class="taqwim-calendar-nav-button" v-slot="{ disabled }">
          <slot name="prev-button" :disabled="disabled">
            <component :is="navigationIcons?.prev ?? ArrowLeft" aria-hidden="true" />
          </slot>
        </HijriCalendarPrev>

        <HijriCalendarHeading class="taqwim-calendar-heading">
          <template v-if="selectableHeading">
            <button
              type="button"
              class="taqwim-calendar-heading-button"
              data-taqwim-heading="month"
              :aria-expanded="picker === 'month'"
              @click="togglePicker('month')"
            >
              {{ months[state.placeholder.hm - 1] }}
            </button>
            <button
              type="button"
              class="taqwim-calendar-heading-button"
              data-taqwim-heading="year"
              :aria-expanded="picker === 'year'"
              @click="togglePicker('year')"
            >
              {{ state.placeholder.hy }}
            </button>
            <span v-if="state.showGregorian && state.secondaryHeadingValue" class="taqwim-calendar-heading-secondary">{{
              state.secondaryHeadingValue
            }}</span>
          </template>
          <template v-else>
            <span>{{ state.headingValue }}</span>
            <span v-if="state.secondaryHeadingValue" class="taqwim-calendar-heading-secondary">{{
              state.secondaryHeadingValue
            }}</span>
          </template>
        </HijriCalendarHeading>

        <HijriCalendarNext v-if="showNavigation" class="taqwim-calendar-nav-button" v-slot="{ disabled }">
          <slot name="next-button" :disabled="disabled">
            <component :is="navigationIcons?.next ?? ArrowRight" aria-hidden="true" />
          </slot>
        </HijriCalendarNext>
      </HijriCalendarHeader>
    </slot>

    <!--
      Rendered inline rather than teleported to <body>: the theme lives on this
      element's ancestors, so a teleported panel would lose it.
    -->
    <div v-if="picker" class="taqwim-calendar-picker">
      <div class="taqwim-calendar-picker-grid">
        <template v-if="picker === 'month'">
          <button
            v-for="(month, index) in months"
            :key="month"
            type="button"
            :data-selected="state.placeholder.hm === index + 1 ? '' : undefined"
            @click="jumpTo({ hm: index + 1 }, state.placeholder)"
          >
            {{ month }}
          </button>
        </template>
        <template v-else>
          <button
            v-for="year in years"
            :key="year"
            type="button"
            :data-selected="state.placeholder.hy === year ? '' : undefined"
            @click="jumpTo({ hy: year }, state.placeholder)"
          >
            {{ year }}
          </button>
        </template>
      </div>
    </div>

    <div v-if="!picker || layout === 'panel'" class="taqwim-calendar-months">
      <HijriCalendarGrid v-for="month in visibleMonths" :key="month.label" :month="month">
        <HijriCalendarGridHead v-if="showWeekdays">
          <HijriCalendarGridRow>
            <HijriCalendarHeadCell v-for="(weekday, index) in weekDays" :key="weekday" class="taqwim-calendar-weekday">
              <slot name="weekday" :weekday="weekday" :index="index">{{ weekday }}</slot>
            </HijriCalendarHeadCell>
          </HijriCalendarGridRow>
        </HijriCalendarGridHead>

        <HijriCalendarGridBody>
          <HijriCalendarGridRow v-for="(week, index) in month.weeks" :key="index">
            <HijriCalendarCell v-for="day in week" :key="`${day.date.hy}-${day.date.hm}-${day.date.hd}`" :day="day">
              <HijriCalendarCellTrigger :day="day" v-slot="cell">
                <slot name="cell" v-bind="cell">
                  <span v-if="cell.secondaryDayValue" class="taqwim-calendar-cell-dates">
                    <span
                      class="taqwim-calendar-cell-primary"
                      data-primary
                      :data-calendar-system="state.dateEmphasis === 'gregorian' ? 'gregorian' : 'hijri'"
                      >{{ cell.primaryDayValue }}</span
                    >
                    <span
                      class="taqwim-calendar-cell-secondary"
                      data-secondary
                      :data-calendar-system="state.dateEmphasis === 'gregorian' ? 'hijri' : 'gregorian'"
                      >{{ cell.secondaryDayValue }}</span
                    >
                  </span>
                  <template v-else>{{ cell.dayValue }}</template>
                </slot>
              </HijriCalendarCellTrigger>
            </HijriCalendarCell>
          </HijriCalendarGridRow>
        </HijriCalendarGridBody>
      </HijriCalendarGrid>
    </div>
  </HijriCalendarRoot>
</template>

// packages/react-styled/src/HijriCalendar.tsx
import type { CalendarDay, HijriCalendarRootProps } from '@taqwim/react'
import {
  HijriCalendarCell,
  HijriCalendarCellTrigger,
  HijriCalendarGrid,
  HijriCalendarGridBody,
  HijriCalendarGridHead,
  HijriCalendarGridRow,
  HijriCalendarHeadCell,
  HijriCalendarHeader,
  HijriCalendarHeading,
  HijriCalendarNext,
  HijriCalendarPrev,
  HijriCalendarRoot,
} from '@taqwim/react'
import { getLocaleData, MAX_HIJRI_YEAR, MIN_HIJRI_YEAR, type HijriDateObject } from '@taqwim/core'
import { useState, type ComponentType, type ReactNode } from 'react'
import { ArrowLeft, ArrowRight } from './icons'

/*
 * Generated from the stylesheets in @taqwim/themes, so a new preset is one
 * CSS file rather than an identical edit in all five styled packages.
 */
import type { HijriCalendarLayout, HijriCalendarTheme } from '@taqwim/themes/names'

export type { HijriCalendarLayout, HijriCalendarTheme }

export type HijriCalendarSize = 'compact' | 'default' | 'large'

export type HijriCalendarCellRenderProps = {
  dayValue: string
  hijriDayValue: string
  gregorianDayValue: string
  primaryDayValue: string
  secondaryDayValue?: string
  day: CalendarDay
}

export interface HijriCalendarProps extends Omit<HijriCalendarRootProps, 'children'> {
  /**
   * Which bundled theme to render with.
   *
   * Applied as `data-taqwim-theme`, so it can also be set on any ancestor to
   * theme a whole subtree, and changed at runtime without swapping stylesheets.
   * @default 'default'
   */
  theme?: HijriCalendarTheme
  /** @default 'default' */
  size?: HijriCalendarSize
  /**
   * How the calendar is arranged.
   *
   * Applied as `data-taqwim-layout`, orthogonal to `theme` and `size` — a
   * theme sets colours, a size sets metrics, a layout sets arrangement.
   * `panel` keeps the grid visible while the month/year picker is open.
   * @default 'default'
   */
  layout?: HijriCalendarLayout
  /** Show the previous/next paging buttons. @default true */
  showNavigation?: boolean
  /** Show the weekday label row. @default true */
  showWeekdays?: boolean
  /**
   * Show the month and year as separate heading buttons that open their pickers.
   * @default true
   */
  selectableHeading?: boolean
  /** Replace the default chevrons. */
  navigationIcons?: { prev?: ComponentType; next?: ComponentType }
  /** Replaces the contents of a day cell. */
  renderCell?: (props: HijriCalendarCellRenderProps) => ReactNode
  /** Replaces a weekday label. */
  renderWeekday?: (props: { weekday: string; index: number }) => ReactNode
}

function renderDefaultCell(cell: HijriCalendarCellRenderProps, dateEmphasis: 'hijri' | 'gregorian'): ReactNode {
  if (cell.secondaryDayValue) {
    return (
      <span className="taqwim-calendar-cell-dates">
        <span
          className="taqwim-calendar-cell-primary"
          data-primary
          data-calendar-system={dateEmphasis === 'gregorian' ? 'gregorian' : 'hijri'}
        >
          {cell.primaryDayValue}
        </span>
        <span
          className="taqwim-calendar-cell-secondary"
          data-secondary
          data-calendar-system={dateEmphasis === 'gregorian' ? 'hijri' : 'gregorian'}
        >
          {cell.secondaryDayValue}
        </span>
      </span>
    )
  }

  return cell.dayValue
}

/*
 * Bounded by what the Umm al-Qura table actually covers. The Vue version
 * previously derived this from `new Date().getFullYear() + 579`, offering years
 * the calendar cannot convert.
 */
const YEARS = Array.from({ length: MAX_HIJRI_YEAR - MIN_HIJRI_YEAR + 1 }, (_, i) => MIN_HIJRI_YEAR + i)

export function HijriCalendar({
  theme = 'default',
  size = 'default',
  layout = 'default',
  showNavigation = true,
  showWeekdays = true,
  selectableHeading = true,
  navigationIcons,
  renderCell,
  renderWeekday,
  ...options
}: HijriCalendarProps): ReactNode {
  const [picker, setPicker] = useState<'month' | 'year' | null>(null)

  const months = getLocaleData(options.locale ?? 'en', 'monthsLong') as string[]
  const PrevIcon = navigationIcons?.prev ?? ArrowLeft
  const NextIcon = navigationIcons?.next ?? ArrowRight

  return (
    <HijriCalendarRoot
      {...options}
      data-taqwim-theme={theme}
      data-taqwim-size={size === 'default' ? undefined : size}
      data-taqwim-layout={layout === 'default' ? undefined : layout}
    >
      {({ months: visibleMonths, weekDays, state, store }) => {
        // Day 1 keeps the jump inside the target month regardless of its length.
        const jumpTo = (part: Partial<HijriDateObject>) => {
          store.setPlaceholder({ ...state.placeholder, ...part, hd: 1 })
          setPicker(null)
        }
        const togglePicker = (which: 'month' | 'year') => setPicker(current => (current === which ? null : which))

        return (
          <>
            <HijriCalendarHeader className="taqwim-calendar-header">
              {showNavigation && (
                <HijriCalendarPrev className="taqwim-calendar-nav-button">
                  <PrevIcon />
                </HijriCalendarPrev>
              )}

              <HijriCalendarHeading className="taqwim-calendar-heading">
                {selectableHeading ? (
                  <>
                    <button
                      type="button"
                      className="taqwim-calendar-heading-button"
                      data-taqwim-heading="month"
                      aria-expanded={picker === 'month'}
                      onClick={() => togglePicker('month')}
                    >
                      {months[state.placeholder.hm - 1]}
                    </button>
                    <button
                      type="button"
                      className="taqwim-calendar-heading-button"
                      data-taqwim-heading="year"
                      aria-expanded={picker === 'year'}
                      onClick={() => togglePicker('year')}
                    >
                      {state.placeholder.hy}
                    </button>
                    {state.showGregorian && state.secondaryHeadingValue && (
                      <span className="taqwim-calendar-heading-secondary">{state.secondaryHeadingValue}</span>
                    )}
                  </>
                ) : (
                  <>
                    <span>{state.headingValue}</span>
                    {state.secondaryHeadingValue && (
                      <span className="taqwim-calendar-heading-secondary">{state.secondaryHeadingValue}</span>
                    )}
                  </>
                )}
              </HijriCalendarHeading>

              {showNavigation && (
                <HijriCalendarNext className="taqwim-calendar-nav-button">
                  <NextIcon />
                </HijriCalendarNext>
              )}
            </HijriCalendarHeader>

            {/*
              Rendered inline rather than in a portal: the theme lives on this
              element's ancestors, so a portalled panel would lose it.
            */}
            {picker && (
              <div className="taqwim-calendar-picker">
                <div className="taqwim-calendar-picker-grid">
                  {picker === 'month'
                    ? months.map((month, index) => (
                        <button
                          key={month}
                          type="button"
                          data-selected={state.placeholder.hm === index + 1 ? '' : undefined}
                          onClick={() => jumpTo({ hm: index + 1 })}
                        >
                          {month}
                        </button>
                      ))
                    : YEARS.map(year => (
                        <button
                          key={year}
                          type="button"
                          data-selected={state.placeholder.hy === year ? '' : undefined}
                          onClick={() => jumpTo({ hy: year })}
                        >
                          {year}
                        </button>
                      ))}
                </div>
              </div>
            )}

            {(!picker || layout === 'panel') && (
              <div className="taqwim-calendar-months">
                {visibleMonths.map(month => (
                  <HijriCalendarGrid key={month.label} month={month}>
                    {showWeekdays && (
                      <HijriCalendarGridHead>
                        <HijriCalendarGridRow>
                          {weekDays.map((weekday, index) => (
                            <HijriCalendarHeadCell key={weekday} className="taqwim-calendar-weekday">
                              {renderWeekday ? renderWeekday({ weekday, index }) : weekday}
                            </HijriCalendarHeadCell>
                          ))}
                        </HijriCalendarGridRow>
                      </HijriCalendarGridHead>
                    )}

                    <HijriCalendarGridBody>
                      {month.weeks.map((week, index) => (
                        <HijriCalendarGridRow key={index}>
                          {week.map(day => (
                            <HijriCalendarCell key={`${day.date.hy}-${day.date.hm}-${day.date.hd}`} day={day}>
                              <HijriCalendarCellTrigger day={day}>
                                {cell =>
                                  renderCell ? renderCell(cell) : renderDefaultCell(cell, state.dateEmphasis ?? 'hijri')
                                }
                              </HijriCalendarCellTrigger>
                            </HijriCalendarCell>
                          ))}
                        </HijriCalendarGridRow>
                      ))}
                    </HijriCalendarGridBody>
                  </HijriCalendarGrid>
                ))}
              </div>
            )}
          </>
        )
      }}
    </HijriCalendarRoot>
  )
}
