// packages/svelte/src/HijriCalendarCell.svelte
<script lang="ts">
  import type { HijriCalendarCellProps } from './types'
  import { getHijriCalendarContext } from './context'

  let { day, children, ...rest }: HijriCalendarCellProps = $props()

  const calendar = getHijriCalendarContext()
  const cellProps = $derived.by(() => {
    void calendar.state
    return calendar.store.getCellProps(day)
  })
</script>

<div
  role="gridcell"
  aria-selected={day.isSelected || undefined}
  aria-disabled={day.isDisabled || day.isUnavailable || undefined}
  data-taqwim-calendar-cell={cellProps['data-taqwim-calendar-cell']}
  data-tooltip={cellProps['data-tooltip']}
  title={cellProps['data-tooltip']}
  data-disabled={day.isDisabled ? '' : undefined}
  data-outside-month={day.isOutsideMonth ? '' : undefined}
  {...rest}
>
  {@render children?.()}
</div>

// packages/vue/src/HijriCalendar/HijriCalendarCell.vue
<script lang="ts">
import type { CalendarDay } from '@taqwim/calendar-core'

export interface HijriCalendarCellProps {
  /** The day this grid cell holds */
  day: CalendarDay
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { injectHijriCalendarRootContext } from './context'

const props = defineProps<HijriCalendarCellProps>()

defineOptions({ name: 'HijriCalendarCell' })

const { store, state } = injectHijriCalendarRootContext()

const cellProps = computed(() => {
  void state.value
  return store.getCellProps(props.day)
})
</script>

<template>
  <div
    role="gridcell"
    :aria-selected="day.isSelected || undefined"
    :aria-disabled="day.isDisabled || day.isUnavailable || undefined"
    :data-taqwim-calendar-cell="cellProps['data-taqwim-calendar-cell']"
    :data-tooltip="cellProps['data-tooltip']"
    :title="cellProps['data-tooltip']"
    :data-disabled="day.isDisabled ? '' : undefined"
    :data-outside-month="day.isOutsideMonth ? '' : undefined"
  >
    <slot />
  </div>
</template>
