// packages/svelte/src/HijriCalendarHeading.svelte
<script lang="ts">
  import { getHijriCalendarContext } from './context'
  import type { DivProps } from './types'
  import type { Snippet } from 'svelte'

  let { children, ...rest }: DivProps & { children?: Snippet<[string]> } = $props()

  const calendar = getHijriCalendarContext()
</script>

<div
  data-taqwim-calendar-heading=""
  data-disabled={calendar.state.disabled ? '' : undefined}
  {...rest}
>
  {#if children}{@render children(calendar.state.headingValue)}{:else}{calendar.state.headingValue}{/if}
</div>

// packages/vue/src/HijriCalendar/HijriCalendarHeading.vue
<script lang="ts">
export interface HijriCalendarHeadingSlot {
  default?: (props: { headingValue: string }) => unknown
}
</script>

<script setup lang="ts">
import { injectHijriCalendarRootContext } from './context'

defineSlots<HijriCalendarHeadingSlot>()

defineOptions({ name: 'HijriCalendarHeading' })

const { state } = injectHijriCalendarRootContext()
</script>

<template>
  <div :data-taqwim-calendar-heading="''" :data-disabled="state.disabled ? '' : undefined">
    <slot :heading-value="state.headingValue">
      {{ state.headingValue }}
    </slot>
  </div>
</template>
